config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get 'about', to: 'static#about'
  get 'contact', to: 'static#contact'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get '/auth/:google_oauth2/callback' => 'sessions#google'

  resources :users
  resources :services
  resources :appointments

  resources :clients do 
    resources :appointments, only: [:show, :index, :new] 
  end

  resources :stylists do 
    resources :services, only: [:show, :index] 
    resources :appointments, only: [:show, :index, :new] 
  end
  
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/client.rb
class Client < ApplicationRecord
    has_many :appointments, :dependent => :destroy
    has_many :stylists, through: :appointments, :dependent => :destroy

    validates_presence_of :name, :email, :phone
    validates :phone, length: { is: 10 }

    before_save :titleize_name
    before_save { email.downcase! }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :require_logged_in
    
    def new
        @client = Client.new
    end
    
    def create
        @client = Client.new(client_params)
        if @client.save
            flash[:success] = "Client Created"
            redirect_to clients_path
        else
            render 'new'
        end
    end

    def index
        if params[:search]
            @clients = Client.where("name LIKE ?", "%#{params[:search]}%")
        else
            @clients = Client.all.order(:name)
        end
    end

    def show
        @client = Client.find(params[:id])
    end

    def edit
        @client = Client.find(params[:id])
    end

    def update
        @client = Client.find(params[:id])
        @client.update(client_params)
        if @client.valid?
            flash[:success] = "Client Saved"
            redirect_to clients_path
        else
            render 'edit'
        end
    end

    def destroy
        Client.find(params[:id]).destroy
        flash[:success] = "Client Deleted"
        redirect_to clients_path
    end

    private
    def client_params
        params.require(:client).permit(:name, :email, :phone, service_ids:[], appointment_ids:[], stylist_ids:[])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
    def display_client_name(appointment)
        if appointment.client 
            client = Client.find(appointment.client_id)
            client.name
        elsif params[:client_id]
            client = Client.find(params[:client_id])
            client.name
        end
    end
end

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>

  <%= render partial: 'errors/error', locals: {object: @client} unless @client.errors.empty? %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %><br><br>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %><br><br>

  <%= f.label :phone %>
  <%= f.phone_field :phone, class: 'form-control' %><br><br>

  <%= f.submit submit_tag %><br>
<% end %>

app/views/clients/edit.html.erb
<h2>Edit Client ID#<%= @client.id %></h2>

<%= render partial: 'form', locals: {submit_tag: 'Save'} %>

<div class="delete">
    <p><%= button_to 'Delete', client_path(@client), method: :delete, data: {confirm: "Are you sure you want to delete '#{@client.name}'?"} %></p>
</div>

app/views/clients/index.html.erb
<h2>Manage Clients</h2>

<span>Search by Name</span>
<%= form_tag(clients_path, method: :get) do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
    <%= link_to "Clear Search", clients_path, class:"cancel-button" if params[:search] %>
<% end %>
<br>

<table>
  <thead><th>Name</th><th>Email</th><th>Phone</th><th>Edit</th><th>Action</th></thead>
  <tbody>
    <% @clients.each do |client| %>
    <tr>
      <td><%= client.name %></td>
      <td><%= client.email %></td>
      <td><%= number_to_phone(client.phone, area_code: true) %></td>
      <td><%= link_to 'Edit', edit_client_path(client) %></td>
      <td><%= link_to "Book Appointment", new_client_appointment_path(client) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="action-link">
  <p><%= link_to 'Create a New Client', new_client_path %></p>
</div>

app/views/clients/new.html.erb
<h2>New Client</h2>

<%= render partial: 'form', locals: {submit_tag: "Submit"} %>