config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get 'about', to: 'static#about'
  get 'contact', to: 'static#contact'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get '/auth/:google_oauth2/callback' => 'sessions#google'

  resources :users
  resources :services
  resources :appointments

  resources :clients do 
    resources :appointments, only: [:show, :index, :new] 
  end

  resources :stylists do 
    resources :services, only: [:show, :index] 
    resources :appointments, only: [:show, :index, :new] 
  end
  
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/stylist.rb
class Stylist < ApplicationRecord
  has_many :appointments, :dependent => :destroy
  has_many :clients, through: :appointments, :dependent => :destroy

  has_many :stylist_services, :dependent => :destroy
  has_many :services, through: :stylist_services, :dependent => :destroy

  before_save { email.downcase! }
  before_save :titleize_name

  validates_presence_of :name, :handle
  validates_presence_of :level, presence: true, numericality: { only_integer: true }
  validates_inclusion_of :level, :in => 0..5, message: 'must be selected from 1-5'
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  validate :has_at_least_one_service?


  private

  def has_at_least_one_service?
    errors.add(:base, 'Must have at least one Service') if self.services.empty?
  end
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
    before_action :require_logged_in, only: [:new, :edit]
    
    def new
        @stylist = Stylist.new
    end

    def create
        @stylist = Stylist.new(stylist_params)
        if @stylist.save
            flash[:success] = "Stylist Created"
            redirect_to @stylist
        else
            render 'new'
        end
    end

    def index
        @stylists = Stylist.all.order(level: :desc, name: :asc)
        @appointments = @appointments.filter_by_stylist(params[:appointment_ids]) if params[:appointment_ids].present?
    end

    def show
        @stylist = Stylist.find(params[:id])
    end

    def edit
        @stylist = Stylist.find(params[:id])
    end

    def update
        @stylist = Stylist.find(params[:id])
        @stylist.update(stylist_params)
        if @stylist.valid?
            flash[:success] = "Stylist Saved"
            redirect_to @stylist
        else
            render 'edit'
        end
    end

    def destroy
        Stylist.find(params[:id]).destroy
        flash[:success] = "Stylist Deleted"
        redirect_to stylists_path
    end

    private

    def stylist_params
        params.require(:stylist).permit(:name, :email, :handle, :level, service_ids:[], appointment_ids:[], client_ids:[]) 
    end
end

app/helpers/stylists_helper.rb
module StylistsHelper
    #display Stylist Name if new Appointment through Stylist
    def display_stylist_name(appointment)
        if appointment.stylist 
            stylist = Stylist.find(appointment.stylist_id)
            stylist.name
        elsif params[:stylist_id]
            stylist = Stylist.find(params[:stylist_id])
            stylist.name
        end
    end

    #grab Stylist Id for new Appointment through Stylist
    def stylist_id(appointment)
        if appointment.stylist_id
            stylist = Stylist.find(appointment.stylist_id)
            stylist.id
        end
    end
end

app/views/stylists/_form.html.erb
<%= form_for @stylist do |f| %>

  <%= render partial: 'errors/error', locals: {object: @stylist} unless @stylist.errors.empty? %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %><br><br>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %><br><br>

  <%= f.label :handle, 'Social Media Handle' %>
  <%= f.text_field :handle, class: 'form-control' %><br><br>
  
  <%= f.label :level, 'Expertise Level' %><br>
  <% (1..5).to_a.each do |number| %>
    <%= f.radio_button :level, number %> 
    <%= f.label :level, number %>
  <% end %><br><br>
  
  <%= f.label :service_ids, "Service(s)" %><br>
  <%= f.collection_check_boxes :service_ids, Service.all, :id, :name %><br><br>

  <%= f.submit submit_tag %>
<% end %>

app/views/stylists/edit.html.erb
<h2>Edit Stylist ID#<%= @stylist.id %></h2>

<%= render partial: 'form', locals: {submit_tag: 'Save'} %>

<div class="delete">
    <p><%= button_to 'Delete', stylist_path(@stylist), method: :delete, data: {confirm: "Are you sure you want to delete '#{@stylist.name}'?"} %></p>
</div>

app/views/stylists/index.html.erb
<h2>All Stylists</h2>

<table class="index">
  <thead><th>Stylist</th><th>Level</th><th>Handle</th></thead>
  <tbody>
    <% @stylists.each do |stylist| %>
    <tr>
      <td><%= link_to stylist.name, stylist_path(stylist) %></td>
      <td><%= stylist.level%></td>
      <td><%= stylist.handle %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="action-link">
  <p><%= link_to 'Create a New Stylist', new_stylist_path if logged_in? %></p>
</div>

app/views/stylists/new.html.erb
<h2>New Stylist</h2>

<%= render partial: "form", locals: {submit_tag: "Submit"} %>

app/views/stylists/show.html.erb
<h2>Stylist Profile</h2>

Name: <strong><%= @stylist.name %> <br></strong>
Email:  <%= @stylist.email %> <br>
Social Media: <%= @stylist.handle %> <br>
Expertise Level:  <%= @stylist.level %> <br>

Services: 
<% order_service_by_name(@stylist.services).each do |service| %>
    <li><%= link_to service.name, stylist_service_path(@stylist.id, service.id) %></li>
<% end %>

<% if logged_in? %>
    <br>
    <div class="action-link">
        <p><%= link_to 'Edit', edit_stylist_path %></p>
    </div>

    <br>
    <div class="action-link">
        <p><%= link_to "Book Appointment with #{@stylist.name}", new_stylist_appointment_path(@stylist) %></p>
    </div>

    <br>
    <p><%= link_to 'View Appointments', stylist_appointments_path(@stylist.id) %></p>
<% end %>