config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get 'about', to: 'static#about'
  get 'contact', to: 'static#contact'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get '/auth/:google_oauth2/callback' => 'sessions#google'

  resources :users
  resources :services
  resources :appointments

  resources :clients do 
    resources :appointments, only: [:show, :index, :new] 
  end

  resources :stylists do 
    resources :services, only: [:show, :index] 
    resources :appointments, only: [:show, :index, :new] 
  end
  
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :client
    belongs_to :stylist

    has_many :appointment_services, :dependent => :destroy
    has_many :services, through: :appointment_services, :dependent => :destroy

    scope :filter_by_stylist, -> (stylist_id) { where stylist_id: stylist_id }

    validate :has_at_least_one_service?
    validates_presence_of :start_time, message: 'error, must choose a Date and Time' 
    validates_presence_of :stylist

    after_validation :stylist_has_service?

    before_save :set_cost, :set_duration, :set_end_time


    def self.by_stylist(stylist_id)
        where(stylist: stylist_id)
    end


    private

    def has_at_least_one_service?
        errors.add(:base, 'Must have at least one Service') if self.services.empty?
    end

    def stylist_has_service?
        self.services.each do |apt_service| 
            errors.add(:base, 'Please choose a different Stylist that offers the services selected') if !self.stylist.services.include?(apt_service) 
        end    
    end 

    def set_cost
        self.cost = self.services.collect {|service| service.price}.sum # self.cost = self.services.pluck(:price).sum
    end

    def set_duration
        self.duration = self.services.collect {|service| service.minutes}.sum 
    end

    def set_end_time
        self.end_time = self.start_time  + (self.duration*60) unless !self.end_time
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :require_logged_in

    def new
        @appointment = Appointment.new(stylist_id: params[:stylist_id], client_id: params[:client_id])
        @stylist = @appointment.stylist if params[:stylist_id]
    end

    def create
        @appointment = Appointment.create(appointment_params)
        if @appointment.valid?
            flash[:success] = "Appointment Created"
            redirect_to @appointment
        else
            render 'new'
        end
    end

    def index
        # start_date = params.fetch(:start_date, Date.today).to_date
        if params[:stylist_id].present?
            @appointments = Appointment.filter_by_stylist(params[:stylist_id]).order(:start_time)
            @stylist = Stylist.find_by(id: params[:stylist_id])
            flash[:success] = "No Appointments currently for Stylist: #{Stylist.find(params[:stylist_id]).name}" if Appointment.find_by(stylist_id: params[:stylist_id]).nil?
        else
            @appointments = Appointment.all.order(:start_time)
        end
        @stylists = Stylist.all.order(:name)
    end

    def show
        @appointment = Appointment.find(params[:id])
        @appointments = Appointment.all
    end

    def edit
        @appointment = Appointment.find(params[:id])
    end

    def update
        @appointment = Appointment.find(params[:id])
        @appointment.update(appointment_params)
        if @appointment.valid?
            flash[:success] = "Appointment Saved"
            redirect_to appointment_path(@appointment)
        else
            render 'edit'
        end
    end

    def destroy
        Appointment.find(params[:id]).destroy
        flash[:success] = "Appointment Deleted"
        redirect_to appointments_path
    end

    private

    def appointment_params
        params.require(:appointment).permit(:cost, :duration, :client_id, :stylist_id, :start_time, :end_time, service_ids:[])
    end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
    def start_time(appointment)
        appointment.start_time.strftime("%I:%M %p")
    end

    def end_time(appointment)
        appointment.end_time.strftime("%I:%M %p")
    end

    def date(appointment)
        appointment.start_time.strftime("%b %d, %Y")
    end
end

app/views/appointments/_appointment_table.html.erb
<table>
  <thead><th>#</th><th>Appointment #ID</th><th>Stylist</th><th>Client</th><th>Cost</th><th>Date</th><th>Time</th></thead>
  <tbody>
    <% appointments.each_with_index do |appointment, index| %>
    <tr>
      <td><%= index += 1 %></td>
      <td><%= link_to "Appointment ##{appointment.id}", appointment_path(appointment) %></td>
      <td><%= display_stylist_name(appointment) %></td>
      <td> <%= display_client_name(appointment) %></td>
      <td>$<%= appointment.cost %></td>
      <td><%= date(appointment) %> </td>
      <td><%= start_time(appointment) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/_calendar.html.erb
<%= month_calendar(events: @appointments) do |date, appointments| %>
  <strong><%= date.day %></strong>

  <small>
  <% 9.upto(20).each do |hour| %>
    <div>
      <%= Time.parse("#{hour}:00").strftime("%l %p") %>

      <div>
      <% appointments.each do |appointment| %>
        <% if appointment.start_time.strftime("%H").to_i  == hour %> 

          <ul>  
            <b><%= link_to "AppointmentID##{appointment.id}", appointment_path(appointment) %></b>
            <br>
            Stylist: <b><%= display_stylist_name(appointment) %></b><br>
            Time: <%= start_time(appointment) %><br>
            Services 
            <% appointment.services.each do |service| %>
            | <%= service.name %>
            <% end %>
          </ul>
        <% end %> 
      <% end %>
      </div>

    </div>
  <% end %>
  </small>
<% end %>

app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>

  <%= render partial: 'errors/error', locals: {object: @appointment} %>
  
  <br> 
  <% if params[:client_id] %>
    <%= f.hidden_field :client_id %>
    <%= f.label :client_id, "Client: #{display_client_name(@appointment)}" %><br>
  <% else %>
    <%= f.label :client_id, 'Choose a Client' %><br>
    <%= f.collection_select :client_id, Client.all.order(:name), :id, :name, include_blank: true %><br>
  <% end %>

  <br>
  <%= f.label :service_ids, 'Choose Service(s)' %><br> 
  <% if params[:stylist_id] %>
    <%= f.hidden_field :stylist_id %>
    <%= f.collection_check_boxes :service_ids, @stylist.services.order(:name), :id, :name %><br> 
  <% else %>
    <%= f.collection_check_boxes :service_ids, Service.all.order(:name), :id, :name %><br>
    <ul>
      <b><u>Stylists per Service:</b></u>
      <br>
      <% Service.all.order(:name).each do |service| %>
        <b><%= service.name %></b>
        <% service.stylists.order(:name).each{|stylist| %> | <%=stylist.name%><% } %><br>
      <% end %>
    </ul>
  <% end %>
  
  <br> 
  <% if params[:stylist_id] %>
    <%= f.hidden_field :stylist_id %>
    <%= f.label :stylist_id, "Stylist: #{display_stylist_name(@appointment)}" %><br>
  <% else %>
  <%= f.label :stylist_id, 'Choose a Stylist' %><br> 
    <%= f.collection_select :stylist_id, Stylist.all.order(:name), :id, :name, include_blank: true %> <br> 
  <% end %>

  <br>
  <%= f.label :start_time, 'Choose a Time' %><br>
  <%= f.datetime_local_field :start_time  %> <br>

  <br>
  <%= f.submit submit_tag %>
<% end %>

app/views/appointments/_table.erb
<table>
  <thead><th></th><th>Appointment ID</th><th>Stylist</th><th>Client</th><th>Cost</th><th>Date</th><th>Time</th></thead>
  <tbody>
    <% appointments.each_with_index do |appointment, index| %>
    <tr>
      <td><%= index += 1 %></td>
      <td><%= link_to "AppointmentID##{appointment.id}", appointment_path(appointment) %></td>
      <td><%= display_stylist_name(appointment) %></td>
      <td><%= display_client_name(appointment) %></td>
      <td>$<%= appointment.cost %></td>
      <td><%= date(appointment) %></td>
      <td><%= start_time(appointment) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/edit.html.erb
<h2>Edit Appointment ID#<%= @appointment.id %></h2>

<%= render partial: 'form', locals: {submit_tag: 'Save'} %>

<div class="delete">
    <p><%= button_to 'Delete', appointment_path(@appointment), method: :delete, data: {confirm: "Are you sure you want to delete 'Appointment ID##{@appointment.id}'?"} %></p>
</div>

app/views/appointments/index.html.erb
<h2>Appointments Calendar</h2>

<%# Filter by Stylist %>
<div class="filter">
    <%= form_tag({}, method: :get, class: "filter") do %> 
        <%= label_tag :stylist_id, 'Choose a Stylist to Filter:' %><br>  
        <%= select_tag :stylist_id, options_from_collection_for_select(@stylists, :id, :name, params[:stylist_id]), include_blank: true %>
        <%= submit_tag "Select" %>
        <%= link_to "Clear Filter", appointments_path, class:"cancel-button" %> 
    <% end %>
</div>

<%# View for All Apts %>
<% if !params[:stylist_id].present? %>
    <h4>Appointment Total: <%= @appointments.count%></h4>
    <%= render partial: 'table', locals: {appointments: @appointments} %>

<%# View for Stylist Apts %>
<% else %>
    <h4>Appointment Total for <%= @stylist.name %>: <%= @appointments.count %></h4>
    <%= render partial: 'table', locals: {appointments: @appointments} %>

    <div class="action-link">
        <br>
        <p><%= link_to "Book Appointment with #{@stylist.name}", new_stylist_appointment_path(@stylist) %></p>
    </div>
<% end %> 

<%# Render Calendar View %>
<br><h3>Calendar View</h3>
<%= render 'calendar' %>

app/views/appointments/new.html.erb
<h2>Make an Appointment</h2> 

<%= render partial: "form", locals: {submit_tag: "Submit"} %>

app/views/appointments/show.html.erb
<h2>Appointment #<%= @appointment.id %></h2>

<%= render partial: 'errors/error', locals: {object: @appointment} %>

<div>

Client: <b><%= @appointment.client.name if @appointment.client %></b><br>
Stylist: <b><%= display_stylist_name(@appointment) %></b><br>

Service(s)
<% @appointment.services.each do |service| %>
  | <b><%= service.name %></b>, 
  Price: <%= service.price %>, 
  Mins: <%= service.minutes %>
<% end %><br>

  Cost: $<%= @appointment.cost %><br>
  Duration: <%= @appointment.duration %> minutes<br> 
  Date: <%= date(@appointment) %><br>
  Time: <%= start_time(@appointment) %><br>

</div>

<br>
<div class="action-link">
  <p><%= link_to 'Edit', edit_appointment_path(@appointment) %></p>
</div>

<br>
<p><%= link_to "View Stylist's Calendar", stylist_appointments_path(stylist_id(@appointment)) %></p>