config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get 'about', to: 'static#about'
  get 'contact', to: 'static#contact'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get '/auth/:google_oauth2/callback' => 'sessions#google'

  resources :users
  resources :services
  resources :appointments

  resources :clients do 
    resources :appointments, only: [:show, :index, :new] 
  end

  resources :stylists do 
    resources :services, only: [:show, :index] 
    resources :appointments, only: [:show, :index, :new] 
  end
  
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalonApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <div class="header">
      <h1>Salon Application</h1>
    </div>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 

    <div class="navbar">
      <%= link_to 'Home', '/' %>
      <%= link_to 'About Us', '/about' %>
      <%= link_to 'Contact Us', '/contact' %>
      <%= link_to 'Stylists', stylists_path %>
      <%= link_to 'Services', services_path %>

      <div class="navbar_logged_in">
        <% if logged_in? %>
          <%= link_to 'Log out', logout_path %>
          <%= link_to 'Profile', current_user %>
          <%= link_to 'Manage Clients', clients_path %>
          <%= link_to 'View All Appointments', appointments_path %>
          <%= link_to 'Book Appointment', new_appointment_path %>
        <% else %>
          <%= link_to 'Sign up', signup_path %>
          <%= link_to "Log in", login_path %>
        <% end %>
      </div>    
    </div>    
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="alert alert-info">
        <%= message %> <%# <%= content_tag(:div, message, class: "alert alert-#{type}") %>
      </div>
    <% end %>

    <div class="main">
      <%= yield %>
    </div>

    <div class="footer">
      <small>
        &copy; 2022 <strong>Salon Application</strong>
        <% if logged_in? %>
          | LOGGED IN AS USER: <%= current_user.name %> / <%= current_user.email %>
        <% end %>
      </small>
    </div>
  </body>
</html>